# Generated by Django 5.2.8 on 2025-11-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('pulsera', 'Pulsera'), ('llavero', 'Llavero'), ('vela', 'Velas'), ('otro', 'Otro')], default='otro', max_length=50),
        ),
    ]
